use_wandb: True

run: 'standard_surgery' # standard_surgery

robot:
  type: 'kuka'
  pose_randomization: False
  pos: [0.0, -0.5, 0.0]
  joint_pos: [1.5, -0.5, 0.0, -1.0, 0.0, 1.6, 0.0]
  randomization:
    position:
      x: [-0.05, 0.05]
      y: [-0.05, 0.05]
      z: [-0.05, 0.05]

robot_drill:
  pose_randomization: False
  pos: [0.0, 0.5, 0.1]
  joint_pos: [-1.5, -0.2, 0.0, -1.3, 0.0, 1.8, 0.0]
  randomization:
    position:
      x: [-0.05, 0.05]
      y: [-0.05, 0.05]
      z: [-0.05, 0.05]

patient:
  pos: [0.2, -0.2, 0.7] # 0.7
  euler_yxz: [-90.0, -90.0, 0.0]
  id_list:  ['s0010'] #, ['s0015'] # 's0024', 's0028', 's0029', 's0030'] # 5 to 1:'s0010', 's0014', 's0015'
  label_res: 0.0015 # m
  target_anatomy: 'vertebrae_L4'

bed:
  pos: [0.0, 0.0, 0.08]
  euler_xyz: [90, 0.0, 90]
  scale: 0.0004

motion_planning:
  standard_surgery:
    joint_pos_rand_max: [0.2, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1] #[0.3, 0.25, 0.2, 0.2, 0.2, 0.2, 0.2] # data collection: 
    vertebra_to_US_2d_pos: [-30.0, 0.0] # [-30, 0.0]
    US_roll_adj: -0.4
    US_target_2d_angle: 1.57
    vertebra_to_US_rand_range:
      x: [-5, 5] 
      z: [-5, 5] 
    US_roll_rand_max: 0.1  # roll noise around US_roll_adj
    US_yaw_rand_max: 0.1 # yaw noise around US_target_2d_angle
    scale: [[2, 2, 0.1]]
    patient_xz_goal: [150, 170, 3.14] # placeholder

  random_probe:
    joint_pos_rand_max: [0.2, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
    vertebra_to_US_2d_pos: [-30, 0.0]
    US_roll_adj: -0.4   # -0.4
    US_target_2d_angle: 1.57
    vertebra_to_US_rand_range:
      x: [-15.0, 15.0] 
      z: [-15.0, 15.0] 
    US_roll_rand_max: 0.0  # roll noise around US_roll_adj
    US_yaw_rand_max: 0.2 # yaw noise around US_target_2d_angle
    scale: [[2, 2, 0.1]]
    patient_xz_goal: [150, 170, 3.14]

observation: 
  style: "large" # large = 7 x 150 x 200, small 25 x 37 x 50
  3D: True
  image_3D_thickness: 7
  downsample: 4
  mode: 'US' # 'seg', 'CT', 'US'
  scale: 0.02 # 0.1, 0.0005, 0.1 for learning-based, 0.02 for model-based
  scale_net: 0.1
  image_3D_offsets: [-12, -8, -4, 0, 4, 8, 12]

action: 
  mode: 'continuous' # 'discrete', 'continuous'
  scale: [0.1, 0.1, 0.1, 1.0, 1.0]  # [0.1, 0.1, 0.1, 1.0, 1.0, 1.0]
  max_action: [0.03, 0.03, 0.03, 0.1, 0.1]  # [0.03, 0.03, 0.03, 0.1, 0.1, 0.1]

reward:
  safe_height: 0.05 # 5cm # 10 cm
  w_pos: 30.0
  w_insertion: 300.0 # 100
  w_angle: 5.0
  w_cost: 0.0 # 


sim:
  episode_length: 5 # 4 10
  patient_xz_range: [[100, 70, 1.5], [180, 200, 3.5]]
  patient_xz_init_range: [[100, 70, 1.5], [180, 200, 3.5]]
  if_use_ct: True
  us: 'net'
  ct_range: [-300, 3000]
  vis_us: True
  vis_int: 5
  vis_seg_map: False
  
if_record_traj: True
record_path: /recordings/robot_US_guided_surgery/


