seed: 11

models:
  separate: False

  policy:
    class: GaussianMixin
    clip_actions: False
    clip_log_std: True
    min_log_std: -20.0
    max_log_std: 2.0
    # initial_log_std: 0.0
    initial_log_std: -2.0   # fine-tuning: meno esplorazione iniziale
    network:
      - name: features_extractor
        input: STATES["image"]
        layers:
          - conv2d: {out_channels: 32, kernel_size: 8, stride: 4, padding: 0}
          - conv2d: {out_channels: 64, kernel_size: 4, stride: 2, padding: 0}
          - conv2d: {out_channels: 64, kernel_size: 3, stride: 1, padding: 0}
          - conv2d: {out_channels: 64, kernel_size: 4, stride: 2, padding: 0}
          - flatten
        activations: relu
      - name: net_pos
        input: STATES["pos"]
        layers: [128, 128, 64]
        activations: elu
      - name: net_quat
        input: STATES["quat"]
        layers: [128, 128, 64]
        activations: elu
      - name: net
        input: concatenate([features_extractor, net_pos, net_quat])
        layers: [512, 256, 128]
        activations: elu
    output: ACTIONS

  value:
    class: DeterministicMixin
    clip_actions: False
    network:
      - name: features_extractor
        input: STATES["image"]
        layers:
          - conv2d: {out_channels: 32, kernel_size: 8, stride: 4, padding: 0}
          - conv2d: {out_channels: 64, kernel_size: 4, stride: 2, padding: 0}
          - conv2d: {out_channels: 64, kernel_size: 3, stride: 1, padding: 0}
          - conv2d: {out_channels: 64, kernel_size: 4, stride: 2, padding: 0}
          - flatten
        activations: relu
      - name: net_pos
        input: STATES["pos"]
        layers: [128, 128, 64]
        activations: elu
      - name: net_quat
        input: STATES["quat"]
        layers: [128, 128, 64]
        activations: elu
      - name: net
        input: concatenate([features_extractor, net_pos, net_quat])
        layers: [512, 256, 128]
        activations: elu
    output: ONE


memory:
  class: RandomMemory
  memory_size: -1


agent:
  class: PPO

  # rollouts: 16
  rollouts: 32

  # learning_epochs: 3
  learning_epochs: 2

  # mini_batches: 32
  mini_batches: 8

  discount_factor: 0.99
  lambda: 0.95

  # learning_rate: 1.0e-04
  learning_rate: 3.0e-05

  learning_rate_scheduler: KLAdaptiveLR
  learning_rate_scheduler_kwargs:
    # kl_threshold: 0.008
    kl_threshold: 0.004

  state_preprocessor: null
  state_preprocessor_kwargs: null

  value_preprocessor: RunningStandardScaler
  value_preprocessor_kwargs: null

  random_timesteps: 0
  learning_starts: 0

  # grad_norm_clip: 1.0
  grad_norm_clip: 0.5

  # ratio_clip: 0.2
  ratio_clip: 0.1

  # value_clip: 0.1
  value_clip: 0.05

  clip_predicted_values: True

  entropy_loss_scale: 0.0

  value_loss_scale: 1.0

  # kl_threshold: 0.0
  kl_threshold: 0.008

  rewards_shaper_scale: 1.0
  time_limit_bootstrap: False

  experiment:
    directory: "navigation_surgery"
    experiment_name: "PPO_finetune_US_net_stable"
    write_interval: auto
    checkpoint_interval: auto


trainer:
  class: SequentialTrainer

  # timesteps: 200000
  timesteps: 50000

  environment_info: log